[package]
default-run = "iroh"
name = "iroh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.46.1", features = ["full"] }
iroh = "0.35.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"